# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: true
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx

## uncomment the following lines to override the default test
# script:
  # - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);'

codecov: true
