# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: true
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

before_script:
  - julia -e 'using Pkg; Pkg.build();'
  - julia -e 'using Pkg;
    Pkg.add(PackageSpec(name="MbedTLS", version="0.6.6"));
    Pkg.pin(PackageSpec(name="MbedTLS", version="0.6.6"));'

## uncomment the following lines to override the default test
script:
  # - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);'

codecov: true

# after_success:
  # push coverage results to Coveralls
   #- julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);' 
